In [4]:
import random

In [30]:
instance =  "../instances/i-2.txt"
random.seed(10)
read_instance = open(instance,'r')
#reward[0] = numpy.random.binomial(1,)

In [22]:
read_instance.seek(0)  
print(read_instance.readline())                

0.4



In [31]:
import pandas as pd
df =pd.read_csv(instance,header=None)
df

0
0  0.1
1  0.2
2  0.3
3  0.4
4  0.5

In [34]:
df[0][1]

0.2

In [38]:
len(df)
import numpy as np

[0 0 0 0 0]


In [76]:
for i in range(20):
   
    reward = np.random.binomial(1,df[0][4])
    print(reward)

1
0
0
1
1
0
1
0
0
0
0
1
0
0
1
1
0
1
1
1


In [242]:
horizon =  2000
instance = "../instances/i-2.txt"
randomSeed = 33

In [243]:
import pandas as pd
import numpy as np
np.random.seed(randomSeed)

In [244]:
def round_robin():
    n = 0
    action_value_t = 0
    df = pd.read_csv(instance, header=None)
    action_value = np.zeros(len(df))
    for i in range(horizon):
        current_arm = i%len(df)
        if i%len(df) == 0:
            n = n+1
        reward = np.random.binomial(1,df[0][current_arm])
        action_value[current_arm] = action_value[current_arm] + reward
        #print(reward)
    #print(action_value)
    regret = max(df[0])*horizon - sum(action_value) 
    return regret

In [245]:
np.random.seed(randomSeed)
x = round_robin()

In [148]:
x

4.0

In [128]:
x

-6.0

In [145]:
max(df[0])

0.5

In [144]:
df

0
0  0.1
1  0.2
2  0.3
3  0.4
4  0.5

In [153]:

t = [1,2,3,4,5]

In [163]:
x = np.random.choice(t)
x

4

In [27]:
import pandas as pd
import numpy as np

In [287]:
horizon =  5000
instance = "../instances/i-2.txt"
randomSeed = 5
epsilon = 0.1

In [288]:
def epsilon_greedy():
    df = pd.read_csv(instance,header=None)
    action_value = np.zeros(len(df))
    action_number = np.arange(len(df))
    arm_count = np.zeros(len(df))
    reward = 0
    for i in range(horizon):
        x = np.random.choice(["eps","eps_conj"],1,p = [epsilon, 1-epsilon])
        
        if i<len(df):
            action_value[i] = np.random.binomial(1,df[0][i])
            arm_count[i] = arm_count[i] + 1
            #print(arm_count)
            
        if(x == "eps" and i>=len(df)):
            y = np.random.choice(action_number)
            arm_count[y] = arm_count[y] + 1
            action_value[y] = (action_value[y]*(arm_count[y]-1) + np.random.binomial(1,df[0][y]))/arm_count[y]
            #print(action_value,y)
            #print(arm_count)
        elif x == "eps_conj" and i>=len(df):
            argmax = action_value.argmax(axis=0)
            arm_count[argmax] = arm_count[argmax] + 1
            action_value[argmax] = (action_value[argmax]*(arm_count[argmax]-1) + np.random.binomial(1,df[0][argmax]))/arm_count[argmax]
            #print(action_value,argmax)
            #print(arm_count)
        #print(x)
        
    for i in range(len(df)):
        reward = reward + action_value[i]*arm_count[i]
    #print(sum(arm_count))
    regret = max(df[0])*horizon - reward
    return regret

In [289]:
np.random.seed(randomSeed)
x = epsilon_greedy()
x 

167.00000000000227

In [206]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
 action_value = np.zeros(5)

In [26]:
#x = "eps" #max(action_value)
if x == "eps" or max(action_value) == 0:
    print("True")

True


In [210]:
x = np.random.choice(["eps","eps_conj"],1,[0.01, 0.99])

In [211]:
x

array(['eps_conj'], dtype='<U8')

In [219]:
t = 0
for i in range(2000):
    x = np.random.choice(["eps","eps_conj"],1,p = [0.01, 0.99])
    if x == "eps":
        t = t+1
print(t)
    

19


In [224]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [241]:
np.random.choice(5)

0

In [263]:
instance = "../instances/i-2.txt"
df = pd.read_csv(instance,header=None)
df

0
0  0.1
1  0.2
2  0.3
3  0.4
4  0.5

In [262]:
df.drop(df.index[1])

0
0  0.1
2  0.3
3  0.4
4  0.5

In [107]:
import numpy as np
import pandas as pd
import math

In [171]:
horizon =  2000
instance = "../instances/i-3.txt"
randomSeed = 33
epsilon = 0.403

In [172]:
def UCB():
    df = pd.read_csv(instance,header=None)
    action_value = np.zeros(len(df))
    arm_count = np.zeros(len(df))
    upper_bound = np.zeros(len(df))
    #t = len(df)
    reward = 0
    for i in range(horizon):
        if i < len(df):
            action_value[i] =  np.random.binomial(1,df[0][i])
            arm_count[i] = arm_count[i] + 1
            #upper_bound[i] = 0 + action_value[i]
            
        else:
            for j in range(len(df)):
                upper_bound[j] = action_value[j] + np.sqrt(2*np.log(i)/arm_count[j])
                
            argmax = upper_bound.argmax(axis = 0)
            arm_count[argmax] = arm_count[argmax] + 1
            action_value[argmax] = ((action_value[argmax]*(arm_count[argmax]-1)) + np.random.binomial(1,df[0][argmax]))/arm_count[argmax]    
            
            
    for i in range(len(df)):
        #print(arm_count[i],action_value[i])
        reward = reward + action_value[i]*arm_count[i]
    #print(max(df[0])*horizon)

    regret = max(df[0])*horizon - reward
    return regret

In [173]:
np.random.seed(randomSeed)
x = UCB()
x 

375.0

In [110]:
np.log(np.exp(1))

1.0

In [123]:
np.random.binomial(1,0.5)

1

In [151]:
x = np.zeros(4)

In [152]:
x[0] = 1
x[1] = 5
x[2] = 6
x[3] = 18

In [153]:
x.argmax(axis=0)

3

In [1]:
import pandas as pd
import numpy as np

In [45]:
def KL_UCB_bound(action_value, arm_count, total_count):
    delta = 0.001
    min = 0 + action_value/arm_count
    max = 1 - delta
    mid_point = (min + max)/2
    threhsold = 0.0001

    if action_value == 0:
        action_value = action_value + delta
    p = action_value/arm_count
    q = (min + max)/2
    constant_line =  (np.log(total_count) + 3*np.log(np.log(total_count)))/arm_count
    KL = p*np.log(p/q) + (1-p)*np.log((1-p)/(1-q))

    while np.abs(constant_line - KL) > threhsold:
       
        q = (min + max)/2
        KL = p*np.log(p/q) + (1-p)*np.log((1-p)/(1-q))

        if constant_line > KL:
            min = q
        else:
            max = q

    return q


In [46]:
x = KL_UCB_bound(20,50,200)

In [47]:
x

0.709590576171875

In [48]:
p = 20/50
q = x

In [49]:
(np.log(200) + 3*np.log(np.log(200)))/50

0.20600970485944828

In [50]:
p*np.log(p/q) + (1-p)*np.log((1-p)/(1-q))

0.20609331162800118

In [51]:
def KL_UCB():
    df = pd.read_csv(instance,header=None)
    action_value = np.zeros(len(df))
    arm_count = np.zeros(len(df))
    upper_bound = np.zeros(len(df))
    reward = 0
    
    for i in range(horizon):
        if i < len(df):
            action_value[i] = np.random.binomial(1,df[0][i])
            arm_count[i] = arm_count[i] + 1

        else:
            for j in range(len(df)):
                upper_bound[j] = KL_UCB_bound(action_value[j],arm_count[j],i+1)

            argmax = upper_bound.argmax(axis=0)
            arm_count[argmax] = arm_count[argmax] + 1
            action_value[argmax] = ((action_value[argmax]*(arm_count[argmax]-1)) + np.random.binomial(1,df[0][argmax]))/arm_count[argmax]

    for i in range(len(df)):
        reward = reward + action_value[i]*arm_count[i]
        #print(max(df[0])*horizon)
    regret = max(df[0])*horizon - reward
    return regret

In [54]:
horizon =  2000
instance = "../instances/i-1.txt"
randomSeed = 33
epsilon = 0.403

In [55]:
np.random.seed(randomSeed)
x = KL_UCB()
x 

/home/sudhirsuman/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in log
  del sys.path[0]
/home/sudhirsuman/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in double_scalars
  del sys.path[0]


377.0